/**
 * @file XYZWriter.h
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#pragma once

#include <fstream>
#include <iomanip>
#include <sstream>

namespace outputWriter {

/**
 * @class XYZWriter
 *
 * This class implements functionality to generate xyz output from a particle vector
 */
class XYZWriter {
 public:
  XYZWriter() = default;
  virtual ~XYZWriter() = default;

  /**
   * @brief Write XYZ output using a provider function.
   * @tparam Function Lambda that takes (std::ofstream&) and writes the lines for particles.
   * @param filler The lambda provided by the simulation.
   * @param num_particles We need the count upfront for the XYZ header.
   */
  template <typename Function>
  void plotParticles(Function filler, int num_particles, const std::string &filename, int iteration) {
    std::ofstream file;
    std::stringstream strstr;
    strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

    file.open(strstr.str().c_str());

    // XYZ Header
    file << num_particles << std::endl;
    file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku." << std::endl;

    // Inversion of Control: Simulation writes the particle lines
    filler(file);

    file.close();
  }
};

}  // namespace outputWriter
