/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <spdlog/spdlog.h>

#include <iostream>

#include "utils/ArrayUtils.h"

Particle::Particle(int type_arg) {
  type = type_arg;
  spdlog::debug("Particle generated!");
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  spdlog::debug("Particle generated by copy!");
}

Particle::Particle(Particle &&other) noexcept
    : x(std::move(other.x)),
      v(std::move(other.v)),
      f(std::move(other.f)),
      old_f(std::move(other.old_f)),
      m(std::move(other.m)),
      type(std::move(other.type)) {
  spdlog::debug("Particle generated by move!");
}

Particle::Particle(const Vector3 &x_arg, const Vector3 &v_arg, const double m_arg, const int type_arg)
    : x(x_arg), v(v_arg), f({0., 0., 0.}), old_f({0., 0., 0.}), m(m_arg), type(type_arg) {
  spdlog::debug("Particle generated!");
}

Particle::~Particle() =
    default;  // hier kein logging, damit keine Probleme entstehen, falls main den logger vor den particeln killed.

const Vector3 &Particle::getX() const { return x; }

const Vector3 &Particle::getV() const { return v; }

const Vector3 &Particle::getF() const { return f; }

const Vector3 &Particle::getOldF() const { return old_f; }

void Particle::setF(const Vector3 &new_f) {
  this->old_f = this->f;
  this->f = new_f;
}

void Particle::addF(const Vector3 &partial_f) { this->f = this->f + partial_f; }

void Particle::subF(const Vector3 &partial_f) { this->f = this->f - partial_f; }

void Particle::setX(const Vector3 &new_x) { this->x = new_x; }

void Particle::setV(const Vector3 &new_v) { this->v = new_v; }

void Particle::setM(const double new_m) { this->m = new_m; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(Particle &other) {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
         (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, Particle &p) {
  stream << p.toString();
  return stream;
}
