/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "Particle.h"

#include <spdlog/spdlog.h>

#include <iostream>

#include "utils/ArrayUtils.h"

Particle::Particle(int type_arg) {
  type = type_arg;
  spdlog::debug("Particle generated!");
  f = {0., 0., 0.};
  old_f = {0., 0., 0.};
  state = 0;
  sigma = 1;
  epsilon = 5;
  x = {0, 0, 0};
  v = {0, 0, 0};
  m = 0;
}

Particle::Particle(const Particle &other) {
  x = other.x;
  v = other.v;
  f = other.f;
  old_f = other.old_f;
  m = other.m;
  type = other.type;
  state = other.state;
  epsilon = other.epsilon;
  sigma = other.sigma;
  spdlog::debug("Particle generated by copy!");
}

Particle::Particle(Particle &&other) noexcept
    : x(other.x),
      v(other.v),
      f(other.f),
      old_f(other.old_f),
      m(other.m),
      type(other.type),
      epsilon(other.epsilon),
      sigma(other.sigma),
      state(other.state) {
  spdlog::debug("Particle generated by move!");
}

Particle::Particle(const Vector3 &x_arg, const Vector3 &v_arg, const double m_arg, const std::optional<double> epsilon,
                   const std::optional<double> sigma, const Vector3 &f_arg, const Vector3 &old_f_arg,
                   const int type_arg)
    : x(x_arg),
      v(v_arg),
      f(f_arg),
      old_f(old_f_arg),
      m(m_arg),
      type(type_arg),
      epsilon(epsilon.value_or(5)),
      sigma(sigma.value_or(1)),
      state(0) {
  spdlog::debug("Particle generated!");
}

Particle::Particle(const Vector3 &x_arg, const Vector3 &v_arg, const double m_arg, const Vector3 &f_arg,
                   const Vector3 &old_f_arg, const int type_arg)
    : Particle(x_arg, v_arg, m_arg, std::nullopt, std::nullopt, f_arg, old_f_arg, type_arg) {
  spdlog::debug("Particle generated!");
};

Particle::Particle(const Vector3 &x_arg, const Vector3 &v_arg, const double m_arg, const int type_arg)
    : Particle(x_arg, v_arg, m_arg, {0, 0, 0}, {0, 0, 0}, type_arg) {}

// hier kein logging, damit keine Probleme entstehen, falls main den logger vor den particeln killed.
Particle::~Particle() = default;

const Vector3 &Particle::getX() const { return x; }

const Vector3 &Particle::getV() const { return v; }

const Vector3 &Particle::getF() const { return f; }

const Vector3 &Particle::getOldF() const { return old_f; }

double Particle::getEpsilon() const { return epsilon; }

double Particle::getSigma() const { return sigma; }

void Particle::setF(const Vector3 &new_f) {
  this->old_f = this->f;
  this->f = new_f;
}

void Particle::addF(const Vector3 &partial_f) { this->f = this->f + partial_f; }

void Particle::subF(const Vector3 &partial_f) { this->f = this->f - partial_f; }

void Particle::setX(const Vector3 &new_x) { this->x = new_x; }

void Particle::setV(const Vector3 &new_v) { this->v = new_v; }

void Particle::setM(const double new_m) { this->m = new_m; }

void Particle::setSigma(const double new_sigma) { this->sigma = new_sigma; }

void Particle::setEpsilon(const double new_epsilon) { this->epsilon = new_epsilon; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

int Particle::getState() const { return state; }

std::string Particle::toString() const {
  std::stringstream stream;
  stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
  return stream.str();
}

bool Particle::operator==(Particle &other) {
  return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
         (old_f == other.old_f);
}

std::ostream &operator<<(std::ostream &stream, Particle &p) {
  stream << p.toString();
  return stream;
}
